### ISSUE TITLE
Test & fix: deadlock & attempt to update a stable object on  incoming_payment_modes#reflect 

### ISSUE THREAD

**Issue by Coren** [ekylibre/erp#289]
Test: if possible.
Backtrace:

----

An ActiveRecord:StatementInvalid occurred in incoming_payment_modes#reflect:

  PG::TRDeadlockDetected: ERROR:  deadlock detected
DETAIL:  Process 17457 waits for ShareLock on transaction 148965; blocked by process 17458.
Process 17458 waits for ShareLock on transaction 148966; blocked by process 17457.
HINT:  See server log for query details.
: UPDATE "journal_entry_items" SET cumulated_absolute_debit = cumulated_absolute_debit + 1276.8, cumulated_absolute_credit = cumulated_absolute_credit + 0.0 WHERE "journal_entry_items"."account_id" = $1 AND ((printed_on = '2014-04-20' AND id > 230 OR printed_on > '2014-04-20')
  app/models/journal_entry_item.rb:159:in `block in <class:JournalEntryItem>'

-----

An ActiveRecord:taleObjectError occurred in incoming_payment_modes#reflect:

  Attempted to update a stale object: IncomingPayment
  app/models/incoming_payment_mode.rb:101:in `block in reflect'

----

It was on:

  * URL        : https://www.ekylibre.org/backend/incoming_payment_modes/2/reflect

**Comment by burisu** [comment]
I cannot reproduce bug for now.
