### ISSUE TITLE
Active list through reflexion are not managed like others

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/erp#316]
in active list,
t.column :born_at
=> good date format in current locale
t.column :born_at, through: :product
=> raw format

same things with nomenclatures reflexions.
t.column :sex
=> translated item
t.column :sex, through: :product
=> raw item (reference_name)

**Comment by burisu** [comment]
ActiveList doesn't know column type with use of `:through` option.
We need to manually add `:datatype` option to force formatting.
