### ISSUE TITLE
Default corporate_styles.xml must be accessible from private directory to prevent links errors with JasperReports compiler

### ISSUE THREAD

**Issue by burisu** [ekylibre/erp#317]
If we use link for private directory, JasperReports cannot use anymore corporate styles, so it crashes.

**Comment by burisu** [comment]
@ionosphere, the error comes from the idea we can use quite easily a common corporate style. I think we can:
  * fully deactivate "corporate styles" in document templates (Does JR dislike missing styles ?) or,
  * copy the default one in private directory and use it. No way to change the default corporate style for every one in one file update

**Comment by ionosphere** [comment]
I agree with the second option

**Comment by burisu** [comment]
Fixed with bd92acd33812224309c485c85643de6f937259e4.
